name: Deploy dashboard project to VPS

on:
    push:
        branches:
            - production

jobs:
    build-push:
        name: Build and push image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout code
                uses: actions/checkout@v3
            